# hexo-theme-indigo
# https://github.com/yscoder/hexo-theme-indigo

# 添加新菜单项遵循以下规则
# menu:
#  link:               fontawesome图标，省略前缀，本主题前缀为 icon-，必须
#    text: About       菜单显示的文字，如果省略即默认与图标一致，首字母会转大写
#    url: /about       链接，绝对或相对路径，必须。
#    target: _blank    是否跳出，省略则在当前页面打开
menu:
  tv:
    text: 我的所有追番
    url: https://lab.yuangezhizao.cn/bangumi
    target: _blank
  music:
    text: 周常出勤记录
    url: https://maimai.yuangezhizao.cn
    target: _blank
  calendar:
    text: 归档时间轴
    url: /archives/index.html
#  tags:
#    text: 标签
#  th-list:
#    text: 分类
#    url: /categories
  book:
    text: 关于 & 留言板
    url: /about.html

# 你的头像url
avatar: https://i1.yuangezhizao.cn/avatar/head.png!webp?imageView2/1/w/80
# avatar link
avatar_link: /
# 头像背景图
brand: https://i1.yuangezhizao.cn/anime/Yuru-Camp-2/nmv2_crop.jpg!webp?imageMogr2/thumbnail/240x

# email
email: root@yuangezhizao.cn

# 设置 Android L Chrome 浏览器状态栏颜色
color: '66CCFF'

# 页面标题
tags_title: 标 签
archives_title: 归档时间轴
categories_title: 分 类

# 文章截断
excerpt_render: true
excerpt_length: 200
excerpt_link: 阅 读 全 文
mathjax: false
archive_yearly: true

# 是否显示文章最后更新时间
show_last_updated: true

# 是否开启分享
share: true

# 是否开启打赏，关闭 reward: false
reward:
  title: 感谢支持，后期会将您加入打赏名单！
  alipay: https://i1.yuangezhizao.cn/pay/alipay.png!webp     #支付宝，关闭设为 false

# 是否开启搜索
search: true

# 是否大屏幕下文章页隐藏导航
hideMenu: true

# 是否开启toc
# toc: false
toc:
  list_number: false  # 是否显示数字排序

# 文章页留言内容，hexo中所有变量及辅助函数等均可调用，具体请查阅 hexo.io
postMessage: 转载请注明出处：<a href="<%- url_for(page.path).replace(/index\.html$/, '') %>" target="_blank" rel="external"><%- page.permalink.replace(/index\.html$/, '') %></a>

# 站长统计，如要开启，输入CNZZ站点id，如 cnzz: 1255152447
cnzz: false

# less
less:
  compress: true
  paths:
    - source/css/style.less

gitment:
   owner: yuangezhizao
   repo: gitment-data
   client_id: f9499ece3391318f822c
   client_secret: ddedcd5b3eaf55dbbb84761136d9ef377e19ace4

# Waline Comment system. https://waline.js.org
waline:
  serverURL: 'https://yuangezhizao.service.tcloudbase.com'

# 规范网址
# 让搜索引擎重定向你的不同域名、不同子域、同域不同目录的站点到你期望的路径
# https://support.google.com/webmasters/answer/139066
# 假设配置为 canonical: http://imys.net，那么从搜索引擎中 www.imys.net 进入会重定向到 imys.net
canonical: false

# 版权起始年份
since_year: 2016

# 用户页面中作者相关的描述性文字，如不需要设为 false
about: 得之坦然，失之淡然，顺其自然，争其必然！

# “不蒜子”访问量统计，详见 http://ibruce.info/2015/04/04/busuanzi/
visit_counter:
  site_uv: 本站已影响
  site_pv: 并帮助

# 动态定义title
title_change:
  normal: (*´∇｀*)被你发现啦
  leave: (つェ⊂)我藏好了哦

# 设置为 true 发布后将使用 unpkg cdn
cdn: false

# 设置为 true 将使用 lightbox render 图片
lightbox: true

# icp备案号  ICP_license: 京ICP备1234556号-1
# ICP_license: false
